In [ ]:
## All the tensor stuff got deleted :)
## moving on to next phase

Covered scalar, vector, matrix tensors, range in tensors, steps, zeros, ones, range alike

# Tensor Data Types

In [ ]:
import torch as torch
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None #data type of tensor (eg float16 or float 32)
                             , device=None,
                             requires_grad=False) #  whether not to track gradients with this tensor gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor* float_32_tensor #sometimes it can throw error, you can never be sure

tensor([ 9., 36., 81.])

In [ ]:
# Create a tensor

some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])

In [ ]:
print(some_tensor)
print(some_tensor.shape)

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])
torch.Size([3, 4])


In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.device

device(type='cpu')

Manipulating Tensors (Tensors Operations)


*   addition
*   subtraction
*   multiplication
*   division
*   matrix multiplication





In [ ]:
# create a tensor
tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,20)

tensor([21, 22, 23])

In [ ]:
# Matrix multiplication
# use this func instead of using loops, this func is implemented in optimizsed
# form hence it is more fats
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# One of the most occuring error -> shape error,
# @ -> also stands for matrix multiplications
# while matrix multiplications, inner dimensions must match

In [ ]:
#### The resulting matrix will have the outer dimensions

# Dealing with shape Error

In [ ]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_b=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])

torch.mm(tensor_A, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the tensor shape issues we can manipulate the shape of one of our tensors using transpose

In [ ]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, amx, sum etc (Tensor aggreration)

In [9]:
# Create a tensor
import torch
x=torch.arange(0,100,10)
# Finding min
torch.min(x)
x.dtype


torch.int64

In [4]:
x.min()

tensor(0)

In [5]:
# Finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [6]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
x.dtype

torch.int64

In [11]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [12]:
x.type(torch.float32).mean()

tensor(45.)

## Finding the position min and max

In [13]:
# index where min val occures
x.argmin()

tensor(0)

In [14]:
# index where max val occurs
x.argmax()

tensor(9)