In [26]:
## All the tensor stuff got deleted :)
## moving on to next phase

Covered scalar, vector, matrix tensors, range in tensors, steps, zeros, ones, range alike

# Tensor Data Types

In [29]:
import torch as torch
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None #data type of tensor (eg float16 or float 32)
                             , device=None,
                             requires_grad=False) #  whether not to track gradients with this tensor gradients
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [36]:
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor* float_32_tensor #sometimes it can throw error, you can never be sure

tensor([ 9., 36., 81.])

In [39]:
# Create a tensor

some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])

In [40]:
print(some_tensor)
print(some_tensor.shape)

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])
torch.Size([3, 4])


In [41]:
some_tensor.size()

torch.Size([3, 4])

In [42]:
some_tensor.dtype

torch.float32

In [43]:
some_tensor.device

device(type='cpu')