In [ ]:
## All the tensor stuff got deleted :)
## moving on to next phase

Covered scalar, vector, matrix tensors, range in tensors, steps, zeros, ones, range alike

# Tensor Data Types

In [ ]:
import torch as torch
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None #data type of tensor (eg float16 or float 32)
                             , device=None,
                             requires_grad=False) #  whether not to track gradients with this tensor gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor* float_32_tensor #sometimes it can throw error, you can never be sure

tensor([ 9., 36., 81.])

In [ ]:
# Create a tensor

some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])

In [ ]:
print(some_tensor)
print(some_tensor.shape)

tensor([[0.6947, 0.9060, 0.2111, 0.8676],
        [0.0768, 0.9601, 0.3705, 0.8919],
        [0.8359, 0.3498, 0.2263, 0.4970]])
torch.Size([3, 4])


In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.device

device(type='cpu')

Manipulating Tensors (Tensors Operations)


*   addition
*   subtraction
*   multiplication
*   division
*   matrix multiplication





In [ ]:
# create a tensor
tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,20)

tensor([21, 22, 23])

In [ ]:
# Matrix multiplication
# use this func instead of using loops, this func is implemented in optimizsed
# form hence it is more fats
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# One of the most occuring error -> shape error,
# @ -> also stands for matrix multiplications
# while matrix multiplications, inner dimensions must match

In [ ]:
#### The resulting matrix will have the outer dimensions

# Dealing with shape Error

In [ ]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_b=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])

torch.mm(tensor_A, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the tensor shape issues we can manipulate the shape of one of our tensors using transpose

In [ ]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, amx, sum etc (Tensor aggreration)

In [9]:
# Create a tensor
import torch
x=torch.arange(0,100,10)
# Finding min
torch.min(x)
x.dtype


torch.int64

In [4]:
x.min()

tensor(0)

In [5]:
# Finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [6]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
x.dtype

torch.int64

In [11]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [12]:
x.type(torch.float32).mean()

tensor(45.)

## Finding the position min and max

In [13]:
# index where min val occures
x.argmin()

tensor(0)

In [14]:
# index where max val occurs
x.argmax()

tensor(9)

## Reshaping, stacking, squeezong and unsequencing tensort

1. Reshaping - reshapes an input tensor to defined shape
2. View- Return a view of an input tensor of certain shape but keep the same
 memory as orginal tensor
3. Stacking - combine mutiple tensors on top of each other or side
by side (vstack, hstack)
4. Squeeze- removed all `1` dimension from a tensor
5. Unsqueeze- add a `1` dimension to a target tensor
6. Permute- Return a view of the input with dimensions permuted (swapped) in a
 certain wau

In [16]:
#Reshaping

x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [17]:
x_reshaped=x.reshape(1,7)
x_reshaped,x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [18]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [19]:
# Size should be compatible
x_reshaped=x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [20]:
# Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [21]:
# Changinf z changed x ( because view of a tensor shares the same memory as original)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [27]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [28]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [30]:
#Sequeeze- removed all single dimensions from target tensors
x


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
x.shape

torch.Size([9])

In [32]:
x.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
x=torch.arange(1,9)

In [34]:
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [36]:
x_reshaped=x.reshape(1,8)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [37]:
x.squeeze()
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [38]:
# unseuence - adds single dimension to a target tensor at a tspecific dimension
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [40]:
x_unsequeezed=x.unsqueeze(dim=0)
x_unsequeezed, x_unsequeezed.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [41]:
x_unsequeezed=x.unsqueeze(dim=1)
x_unsequeezed, x_unsequeezed.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]),
 torch.Size([8, 1]))

In [43]:
# torch.permutate - rearrange the dimensions of a tagret tensor in a specified order
x_original=torch.rand(size=(224,224,3)) # height, width, color_channels
# Permute the original tensor to rearrnage the axis or order
x_permutated= x_original.permute(2,0,1)
x_original.shape, x_permutated.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NUmpy

In [44]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [45]:
# Indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
x[0][0] #x[0,0]

tensor([1, 2, 3])

In [48]:
x[0,0]

tensor([1, 2, 3])

In [49]:
# You can also use ":" to select "all" of a target dimensions
x[:,0]

tensor([[1, 2, 3]])

In [50]:
# Get all values of 0th and Ist dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [51]:
# Get all values of the 0 dimension but only the 1 index vlaue of Ist and End dim
x[:,1,1]

tensor([5])

In [52]:
# Get index 0 of the 0th and Ist dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [53]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [54]:
# Index on x to return 3, 6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Py Torch tensors & NumPy

NumPy is a popular scientific Python numerical computing library, And becuase
of this, PyTorch has functionality to interact with it.

*   Data in NumPy, want in PyTorch tensor `torch.from_numpy(ndarray)`
*   PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [57]:
# NumPy array to tensor
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
# when converting from numpy -> pyTorch, pyTorch reflects numpy's default datatype of float 64 unless
# specified otherwise
array,tensor,array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'))

In [62]:
tensor=torch.from_numpy(array).type(torch.float32)
tensor,tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [65]:
# Change the value of array
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [66]:
# Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

` start with random numbers -> tensor operations -> update random numbers to try
  and make them better representations of the data -> again -> again -> adain ..`

  TO reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
  Essentially what the random seed does is "flavour" the randomness

In [69]:
torch.rand(3,3)

tensor([[0.8678, 0.9679, 0.2286],
        [0.6929, 0.1005, 0.4553],
        [0.4854, 0.1963, 0.3087]])

In [71]:
# Lets make some random but reproducible tensors

RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)
random_tensor_a=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_b=torch.rand(3,4);

print(random_tensor_a==random_tensor_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU ( and making faster computation)

GPUs =faster computation on numbers , tahnaks to CUDS + NIVIDIA hardware +PyTorch

### 1. Getting a GPU

1.Easiest - Use Collab for a free GPU (Options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and the investment
to purchase a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the
cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit os setting up, to do
this refer to PyTorch setup documentation


In [72]:
# Check for GPU acesss with PyTorch

In [73]:
torch.cuda.is_available()

False

In [75]:
# Setup device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [76]:
# Count no of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is becuase using a GPU results
in faster computations

In [78]:
#Cretae a tensor(default on the cpu)

tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [79]:
# Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back the the CPU

In [81]:
# If tensor is on GPU, cant tanform it to Numpy
# To fix the GPU tensor with NUMPY issue, we can first set it to the CPU

tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])